Floweure/src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 150)]
    private ?string $contenu = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?User $auteur = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?Product $product = null;

        public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): static
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getAuteur(): ?User
    {
        return $this->auteur;
    }

    public function setAuteur(?User $auteur): static
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }
}

Floweure/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Doctrine\Bundle\FixturesBundle\Fixture;

use Symfony\Component\HttpFoundation\File\File;


#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $descrip = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'img')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255)]
    private ?string $img = null;

    #[ORM\Column]
    private ?int $qte = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Commentaire::class)]
    private Collection $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescrip(): ?string
    {
        return $this->descrip;
    }

    public function setDescrip(string $descrip): static
    {
        $this->descrip = $descrip;

        return $this;
    }

    
    public function getImg(): ?string
    {
        return $this->img;
    }
    
    public function setImg(string $img): static
    {
        $this->img = $img;
        
        return $this;
    }
    
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

    }

    public function getImageFile(): ?File
    {
    return $this->imageFile;
    }
    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(int $qte): static
    {
        $this->qte = $qte;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setProduct($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getProduct() === $this) {
                $commentaire->setProduct(null);
            }
        }

        return $this;
    }
}

Floweure/src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;



class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('descrip')
            ->add('imageFile',VichImageType::class, [
                'required' => false,
                'allow_delete' => true,
                'download_uri' =>false,
                'label' =>false
            ])
            ->add('qte')
            ->add('prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

Floweure/src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
//include paginator interface
use Knp\Component\Pager\PaginatorInterface;

#[Route('/product')]

class ProductController extends AbstractController
{
    #[Route('/', name: 'app_product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $pagination = $paginator->paginate(
            $productRepository-> productInHome(),
            $request->query->get('page', 1),
            10
        );


        return $this->render('product/index.html.twig', [
            // 'products' => $productRepository->findAll(),
            'pagination' => $pagination
        ]);
    }

    #[Route('/new', name: 'app_product_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,

        ]);
    }

    #[Route('/show/{id}', name: 'app_product_show', methods: ['GET','POST'])]
    public function show(Product $product, Request $request, EntityManagerInterface $entityManager, CommentaireRepository $commentaireRepository): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentaire->setAuteur($this->getUser());

            $commentaire->setProduct($product);

            $entityManager->persist($commentaire);
            $entityManager->flush();

            // return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
            return $this->redirectToRoute('app_product_show', ['id' =>$product->getId()]);

        }

        return $this->render('product/show.html.twig', [
            'product' => $product,
            'form' => $form,
            'commentaires' => $commentaireRepository->findBy(['product' => $product])
        ]);
    }

    #[Route('/{id}/edit', name: 'app_product_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Product $product, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_product_delete', methods: ['POST'])]
    public function delete(Request $request, Product $product, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
    }
}

Floweure/templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

Floweure/templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Floweure/templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

Floweure/templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
<link rel="stylesheet" href="/css/product.css">
<section class="container">
    <h1>Nos offres</h1>

    <div id="products">
        {% for product in pagination %}

        <div class="products_card">
            <div class="card_img">
                <img src="{{ product.img }}" width="100%"  alt="">
            </div>
            <h3> {{ product.titre }} </h3>
            <p>{{ product.prix }}€</p>
            <a class="details" href="{{ path('app_product_show', {'id': product.id}) }}">Voir détails</a>
            <a href="{{path('app_ajout_panier', {'id': product.id})}}"><i class="fa-solid fa-cart-shopping"></i></a>
        </div>

        {% else %}
        <p>pas de produits</p>
        {% endfor %}

    </div>
    <div id="pagination">
        {{ knp_pagination_render(pagination)}}
    </div>
</section>
{% endblock %}

Floweure/templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('app_product_index') }}">back to list</a>
{% endblock %}

Floweure/templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
<h1>Product</h1>

<table class="table">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ product.id }}</td>
        </tr>
        <tr>
            <th>Titre</th>
            <td>{{ product.titre }}</td>
        </tr>
        <tr>
            <th>Descrip</th>
            <td>{{ product.descrip }}</td>
        </tr>
        <tr>
            <th>Img</th>
            <td>{{ product.img }}</td>
        </tr>
        <tr>
            <th>Qte</th>
            <td>{{ product.qte }}</td>
        </tr>
        <tr>
            <th>Prix</th>
            <td>{{ product.prix }}</td>
        </tr>
    </tbody>
</table>

<a href="{{ path('app_product_index') }}">Revenir a la liste</a>

                    {% if app.user %}
                    {% for role in app.user.roles %}
                    {% if role == "ROLE_ADMIN" %}

                    <br> <button><a href="{{ path('app_product_edit', {'id': product.id}) }}">edit</a></button>

                    {{ include('product/_delete_form.html.twig') }}
                    {% else %}
                    {% endif %}
                    {% endfor %}
                    {% endif %}





<hr>
<div class="commentaire">
    <h4>Listing des commentaires</h4>
    {% for commentaire in commentaires %}

    Posté par <i>{{commentaire.auteur.pseudo}}</i>, le
    {{ commentaire.createdAt ? commentaire.createdAt|date('d-m-Y H:i:s') : '' }}
    <p>
        {{ commentaire.contenu}}
    </p>

    {% endfor %}




{# {% for commentaire in commentaires %}s
        {{commentaire.contenu}} par
        {{commentaire.auteur.pseudo}}
    {% endfor %} #}

    {% if app.user %}
        <hr>
        <h4>Laisser votre commentaire</h4>
        {{ include('commentaire/_form.html.twig') }}
    </div>

                {% endif %}
{% endblock %}